services:
  - type: web
    name: teach-me-in-my-language
    env: python
    pythonVersion: "3.11"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p model_cache
      mkdir -p static
    startCommand: python run.py
    envVars:
      - key: HF_API_KEY
        sync: false
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "INFO"
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: model-cache
      mountPath: /model_cache
      sizeGB: 1 