services:
  - type: web
    name: teach-me-in-my-language
    env: python
    pythonVersion: "3.11"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p model_cache
      mkdir -p static
    startCommand: gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --log-level info
    envVars:
      - key: HF_API_KEY
        sync: false
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "INFO"
      - key: GUNICORN_CMD_ARGS
        value: "--worker-class uvicorn.workers.UvicornWorker"
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: model-cache
      mountPath: /model_cache
      sizeGB: 1 