services:
  - type: web
    name: teach-me-in-my-language
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info
    envVars:
      - key: HF_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MODEL_CACHE_DIR
        value: /opt/render/model_cache
    disk:
      name: model-cache
      mountPath: /opt/render/model_cache
      sizeGB: 1
    autoDeploy: true
    plan: free
    healthCheckPath: / 